apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-executor-deployment"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.executor.app }}"
  replicas: {{ .Values.executor.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ .Values.executor.app }}"
    spec:
      containers:
        - name: "{{ .Release.Name }}-executor"
          image: "{{ .Values.executor.repository }}:{{ .Values.executor.tag }}"
          ports:
            - containerPort: {{ .Values.executor.port }}
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: PASSWORD
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: ENV
            - name: APP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: APP_HOST
            - name: ARX_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: ARX_URL
            - name: RUNNER_HEALTHCHECKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: RUNNER_HEALTHCHECKER_USERNAME
            - name: RUNNER_HEALTHCHECKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: RUNNER_HEALTHCHECKER_PASSWORD
            - name: RUNNER_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: RUNNER_HOST
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: DATABASE_PASSWORD
            - name: PROMETHEUS_CLIENT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: PROMETHEUS_CLIENT_ADDRESS
            - name: SLACK_HOOK
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: SLACK_HOOK
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.executor.secret.name }}
                  key: APP_NAME
