apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-executor-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.name }}
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.executor.ingress.host }}
      secretName: executor-tls
  rules:
    - host: {{ .Values.executor.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "{{ .Values.executor.ingress.path }}"
            backend:
              service:
                name: executor-service
                port:
                  number: {{ .Values.executor.ingress.port }}
