apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.executor.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  ENV: {{ include "env" . }}
  USERNAME: {{ include "executor.username" . }}
  PASSWORD: {{ include "executor.password" . }}
  ARX_URL: {{ .Values.arx.url | b64enc }}
  APP_NAME: {{ printf "executor-%s" .Values.organization.id | b64enc  }}
  APP_HOST: {{ printf "https://%s" .Values.executor.ingress.host | b64enc }}
  PROMETHEUS_CLIENT_ADDRESS: {{ .Values.executor.secret.PROMETHEUS_CLIENT_ADDRESS | b64enc }}
  RUNNER_HEALTHCHECKER_USERNAME: {{ include "runnerHealthchecker.username" . }}
  RUNNER_HEALTHCHECKER_PASSWORD: {{ include "runnerHealthchecker.password" . }}
  RUNNER_HOST: {{ .Values.executor.secret.RUNNER_HOST | b64enc }}
