apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.executor.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  USERNAME: {{ .Values.executor.secret.USERNAME | b64enc }}
  PASSWORD: {{ .Values.executor.secret.PASSWORD | b64enc }}
  ENV: {{ .Values.executor.secret.ENV | b64enc }}
  APP_HOST: {{ .Values.executor.secret.APP_HOST | b64enc }}
  ARX_URL: {{ .Values.executor.secret.ARX_URL | b64enc }}
  RUNNER_HEALTHCHECKER_USERNAME: {{ .Values.executor.secret.RUNNER_HEALTHCHECKER_USERNAME | b64enc }}
  RUNNER_HEALTHCHECKER_PASSWORD: {{ .Values.executor.secret.RUNNER_HEALTHCHECKER_PASSWORD | b64enc }}
  RUNNER_HOST: {{ .Values.executor.secret.RUNNER_HOST | b64enc }}
  DATABASE_HOST: {{ .Values.executor.secret.DATABASE_HOST | b64enc }}
  DATABASE_PORT: {{ .Values.executor.secret.DATABASE_PORT | b64enc }}
  DATABASE_NAME: {{ .Values.executor.secret.DATABASE_NAME | b64enc }}
  DATABASE_USERNAME: {{ .Values.executor.secret.DATABASE_USERNAME | b64enc }}
  DATABASE_PASSWORD: {{ .Values.executor.secret.DATABASE_PASSWORD | b64enc }}
  PROMETHEUS_CLIENT_ADDRESS: {{ .Values.executor.secret.PROMETHEUS_CLIENT_ADDRESS | b64enc }}
  SLACK_HOOK: {{ .Values.executor.secret.SLACK_HOOK | b64enc }}
  APP_NAME: {{ .Values.executor.secret.APP_NAME | b64enc }}
