apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-executor-service
spec:
  selector:
    app: {{ .Values.executor.app }}
  type: {{ .Values.executor.service.type }}
  ports:
    - name: {{ .Values.executor.service.name }}
      port: {{ .Values.executor.service.port }}
      targetPort: {{ .Values.executor.service.targetPort }}