apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-runner-healthchecker-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.runnerHealthchecker.app }}
  replicas: {{ .Values.runnerHealthchecker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.runnerHealthchecker.app }}
    spec:
      containers:
        - name: {{.Release.Name}}-runner-healthchecker
          image: {{ .Values.runnerHealthchecker.repository }}:{{ .Values.runnerHealthchecker.tag }}
          ports:
            - containerPort: {{ .Values.runnerHealthchecker.port }}
          env:
            - name: RUNNER_HEALTHCHECKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runnerHealthchecker.secret.name }}
                  key: RUNNER_HEALTHCHECKER_USERNAME
            - name: RUNNER_HEALTHCHECKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runnerHealthchecker.secret.name }}
                  key: RUNNER_HEALTHCHECKER_PASSWORD
            - name: RUNNER_HEALTHCHECKER_NAME
              valueFrom:
                secretKeyRef:
                  key: RUNNER_HEALTHCHECKER_NAME
                  name: {{ .Values.runnerHealthchecker.secret.name }}
            - name: RUNNER_HEALTHCHECKER_HOST
              valueFrom:
                secretKeyRef:
                  key: RUNNER_HEALTHCHECKER_HOST
                  name: {{ .Values.runnerHealthchecker.secret.name }}
            - name: RUNNER_HEALTHCHECKER_ARX_URL
              valueFrom:
                secretKeyRef:
                  key: RUNNER_HEALTHCHECKER_ARX_URL
                  name: {{ .Values.runnerHealthchecker.secret.name }}
