apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-runner-healthchecker-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certManager.name }}
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.runnerHealthchecker.ingress.host }}
      secretName: {{ .Release.Name }}-runner-healthchecker-tls
  rules:
    - host: {{ .Values.runnerHealthchecker.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.runnerHealthchecker.service.name }}
                port:
                  number: {{ .Values.runnerHealthchecker.service.port }}
