apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.runnerHealthchecker.secret.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  ENV: {{ include "env" . }}
  RUNNER_HEALTHCHECKER_USERNAME: {{ include "runnerHealthchecker.username" . }}
  RUNNER_HEALTHCHECKER_PASSWORD: {{ include "runnerHealthchecker.password" . }}
  RUNNER_HEALTHCHECKER_NAME: {{ printf "runner-healthchecker-%s" .Values.organization.id | b64enc  }}
  RUNNER_HEALTHCHECKER_HOST: {{ printf "https://%s" .Values.runnerHealthchecker.ingress.host | b64enc }}
  RUNNER_HEALTHCHECKER_ARX_URL: {{ .Values.arx.url | b64enc }}
