apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.runnerHealthchecker.secret.name }}
type: Opaque
data:
  RUNNER_HEALTHCHECKER_USERNAME: {{ .Values.runnerHealthchecker.secret.RUNNER_HEALTHCHECKER_USERNAME | b64enc }}
  RUNNER_HEALTHCHECKER_PASSWORD: {{ .Values.runnerHealthchecker.secret.RUNNER_HEALTHCHECKER_PASSWORD | b64enc }}
  ENV: {{ .Values.runnerHealthchecker.secret.ENV | b64enc }}
  RUNNER_HEALTHCHECKER_NAME: {{ .Values.runnerHealthchecker.secret.RUNNER_HEALTHCHECKER_NAME | b64enc }}
  RUNNER_HEALTHCHECKER_HOST: {{ .Values.runnerHealthchecker.secret.RUNNER_HEALTHCHECKER_HOST | b64enc }}
  RUNNER_HEALTHCHECKER_ARX_URL: {{ .Values.runnerHealthchecker.secret.RUNNER_HEALTHCHECKER_ARX_URL | b64enc }}
