apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-runner-healthchecker-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.runnerHealthchecker.app }}
  type: {{ .Values.runnerHealthchecker.service.type }}
  ports:
    - name: {{ .Values.runnerHealthchecker.service.name }}
      port: {{ .Values.runnerHealthchecker.service.port }}
      targetPort: {{ .Values.runnerHealthchecker.service.targetPort }}
