{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.name }}
spec:
  acme:
    server: {{ .Values.certManager.server }}
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretRef.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end -}}
